### ISSUE TITLE
Are you currently actively working on apoc?

### ISSUE THREAD

**Issue by jexp** [hacksparrow/apoc#15]
I think it's a nice framework and it is already referenced in some places like the express documentation.

http://expressjs.com/guide/database-integration.html

So it would be good to keep it up to date with recent features in Neo4j.

Like auth in 2.2, the transactional API also across multiple requests and multiple statements per request.

Going forward the binary protocol and more.

Please let me know also if you need something from us.

Besides the readme, are there other blog posts, articles, screencasts about apoc ?

I'd love to list it at neo4j.com/developer/javascript

Cheers, Michael

**Comment by hacksparrow** [comment]
Thanks for the interest, it will help me continue work the project.

**Comment by hacksparrow** [comment]
Just released the latest version 2.0.1, with authentication and support for multiple statements per request. This version comes with an improved API and a set of unit tests.
