### ISSUE TITLE
Loading Environment Variables

### ISSUE THREAD

**Issue by rodaan** [hacksparrow/apoc#21]
Hi,
How do we go about loading our .env file so apoc can connect to our Neo4j database? We've tried putting a .env file in our project folder and using a module called dotenv but it doesn't seem to be working. It only seems to work when the .apoc.yml file setup but we're tried to avoid that.

Can you help us?

Thanks,
rodaan

**Comment by hacksparrow** [comment]
You can use https://www.npmjs.com/package/node-env-file to populate the ENV vars. Make sure to load it before apoc is loaded. Hope it helps.

**Comment by rodaan** [comment]
Hi again,
It didn't work out for us. It seems that the env file's contents are being loaded but when apoc attempts to connect to the Neo4j database it gives us this error still:
{ Error: getaddrinfo ENOTFOUND undefined undefined:80
   at errnoException (dns.js:28:10)
   at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:79:26)
 code: 'ENOTFOUND',
 errno: 'ENOTFOUND',
 syscall: 'getaddrinfo',
 hostname: 'undefined',
 host: 'undefined',
 port: 80 }

This is what our env file looks like:
NEO4J_PROTOCOL=http
NEO4J_HOST=127.0.0.1
NEO4J_PORT=7474
NEO4J_USERNAME=neo4j
NEO4J_PASSWORD=123

Is there anything wrong with how we are doing it?

Thanks,
Rodaan

**Comment by hacksparrow** [comment]
Do this:

```
var env = require('node-env-file');
env(__dirname + '/.env');
```

before you do this:

```
var apoc = require('apoc');
```

and make sure the path to the `.env` file is correct.

**Comment by rodaan** [comment]
Hi again,
Yea we did that already in our server file but it didn't work for us. Any other suggestions?

Thanks,
Rodaan

**Comment by hacksparrow** [comment]
Do you see the ENV vars when you do this?

```
var env = require('node-env-file');
env(__dirname + '/.env');
console.log(process.env);
```

**Comment by rodaan** [comment]
Yes we see those coming in but for some reason Apoc does not recognize them and can't connect to our database.

**Comment by hacksparrow** [comment]
Can you share then OS, Neo4j, and Node.js version? Also, are you using any framework?

**Comment by rodaan** [comment]
We're running it locally on MacOS version 10.11.4 on El Capitan. The Node.js version is 6.2. Neo4j is 3.0.3. We're using Express as our framework.

**Comment by hacksparrow** [comment]
Mine's MacOS 10.11.15, Node.js 6.2.2, and Neo4j 3.0.3. It works just fine.

Can you see if this works on your system?

```
var env = require('node-env-file');
env(__dirname + '/.env');

var apoc = require('apoc')
var query = apoc.query('CREATE (n:User { name: "Georges" })')

query.exec().then(function (result) {
  console.log(result)
}, function (fail) {
  console.log(fail)
})
```

Make sure the path to the `.env` file is absolutely correct.

**Comment by rodaan** [comment]
We've tried that. We can get the process env variables to print out and load correctly when we console log them but for some reason when we call the query method apoc is unable to connect to the database.

**Comment by hacksparrow** [comment]
Can you save the code I pasted above in a file, execute it, and share the outcome?

**Comment by rodaan** [comment]
Oh it looks like it works! Sorry about the hassle. We ended up using what you wrote line by line and that fixed it. We weren't using the node-env-file module correctly it seems.

Thanks so much for your patience!

**Comment by hacksparrow** [comment]
Good to know. All the best!

**Comment by rodaan** [comment]
Hi again,
Okay so its weird but we currently have a service based architecture. I just put it into the server that is the one interacting with Neo4j but it looks like it doesn't seem to work in there. I get this as an error message using the code you put above:

{ Error: getaddrinfo ENOTFOUND undefined undefined:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:79:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'undefined',
  host: 'undefined',
  port: 80 }
